# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 11:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0002_auto_20161220_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
