# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0004_auto_20161220_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='SN',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='machine',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='machine',
            name='state',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='machine',
            name='temperature',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='machine',
            name='time',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='machine',
            name='warning',
            field=models.CharField(max_length=10),
        ),
    ]
