# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0007_auto_20161220_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
