# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 12:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0011_auto_20161223_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state_log',
            name='machine',
        ),
        migrations.RemoveField(
            model_name='temperature_log',
            name='machine',
        ),
        migrations.RemoveField(
            model_name='warning_log',
            name='machine',
        ),
        migrations.DeleteModel(
            name='State_log',
        ),
        migrations.DeleteModel(
            name='Temperature_log',
        ),
        migrations.DeleteModel(
            name='Warning_log',
        ),
    ]
