# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('tel', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=10)),
                ('QQ', models.CharField(max_length=10)),
            ],
        ),
    ]
