# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0005_auto_20161220_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='SN',
            field=models.CharField(max_length=10, unique='true'),
        ),
    ]
