# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 05:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0006_auto_20161220_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_temperature', models.CharField(max_length=10)),
                ('temperature_change_time', models.CharField(max_length=20)),
                ('history_warning', models.CharField(max_length=10)),
                ('warning_change_time', models.CharField(max_length=20)),
                ('history_open_close', models.CharField(max_length=10)),
                ('open_close_time', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='machine',
            name='limit',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='machine',
            name='time',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='machine_log',
            name='SN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='default.Machine'),
        ),
    ]
