# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 07:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0009_auto_20161223_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machine_log',
            old_name='SN',
            new_name='machine',
        ),
    ]
