# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 12:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0012_auto_20161223_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='State_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_state', models.CharField(max_length=10)),
                ('state_change_time', models.CharField(max_length=20)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='default.Machine')),
            ],
        ),
        migrations.CreateModel(
            name='Temperature_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_temperature', models.CharField(max_length=10)),
                ('temperature_change_time', models.CharField(max_length=20)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='default.Machine')),
            ],
        ),
        migrations.CreateModel(
            name='Warning_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_warning', models.CharField(max_length=10)),
                ('warning_change_time', models.CharField(max_length=20)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='default.Machine')),
            ],
        ),
    ]
